plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0'
group = 'com.yourname.yellowduck'
archivesBaseName = 'yellowduck'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                yellowduck {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }

    // Polymesh 使用的 Modrinth 仓库
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.29'
    implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20.1:4.7.1.1')

    // Polymesh - glTF/GLB 渲染库（已替换 MCglTF）
    implementation fg.deobf("maven.modrinth:GmPRqxTy:jJiQUzrS")
}
