plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0'
group = 'com.yourname.yellowduck'
archivesBaseName = 'yellowduck'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                yellowduck {
                    source sourceSets.main
                }
            }
        }
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "yellowduck",
                "Specification-Vendor"    : "yourname",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "yourname",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }

    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }

    // GeckoLib
    maven { url = 'https://www.cursemaven.com' }
}

dependencies {
    // Minecraft 1.20.1 / Forge 47.4.10
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'

    // GeckoLib 4.7.1.1
    implementation fg.deobf("curse.maven:geckolib-388172:6312918")

    // Polymesh 1.0.0
    // 文件位置：
    // libs/polymesh-1.0.0-forge.jar
    implementation fg.deobf(files("libs/polymesh-1.0.0-forge.jar"))

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}
