modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="yellowduck"
version="1.0"
displayName="tianmingBoss"
description="netcraft扩展"
mixins=["yellowduck.mixins.json"]
