package com.yourname.yellowduck.cleopatra;
import com.mojang.blaze3d.vertex.*;import com.mojang.math.Axis;import com.yourname.yellowduck.YellowDuckMod;import dev.phe.polymesh.animation.AnimationController;import dev.phe.polymesh.api.GltfRenderOptions;import dev.phe.polymesh.client.GltfEntityRenderer;import net.minecraft.client.renderer.*;import net.minecraft.client.renderer.texture.OverlayTexture;import net.minecraft.client.renderer.entity.*;import net.minecraft.resources.ResourceLocation;import net.minecraft.util.Mth;import net.minecraft.world.entity.Entity;import net.minecraftforge.api.distmarker.Dist;import net.minecraftforge.client.event.EntityRenderersEvent;import net.minecraftforge.eventbus.api.SubscribeEvent;import net.minecraftforge.fml.common.Mod;import org.joml.Matrix4f;import software.bernie.geckolib.model.GeoModel;import software.bernie.geckolib.renderer.GeoEntityRenderer;
@Mod.EventBusSubscriber(modid=YellowDuckMod.MOD_ID,bus=Mod.EventBusSubscriber.Bus.MOD,value=Dist.CLIENT)
public final class CleopatraClient {@SubscribeEvent public static void register(EntityRenderersEvent.RegisterRenderers e){e.registerEntityRenderer(CleopatraEntities.BOSS.get(),BossRenderer::new);e.registerEntityRenderer(CleopatraEntities.SNAKE_POISON.get(),c->new SnakeRenderer(c,"cleopatra_snake_poison"));e.registerEntityRenderer(CleopatraEntities.SNAKE_FIRE.get(),c->new SnakeRenderer(c,"cleopatra_snake_fire"));e.registerEntityRenderer(CleopatraEntities.SNAKE_ICE.get(),c->new SnakeRenderer(c,"cleopatra_snake_ice"));e.registerEntityRenderer(CleopatraEntities.SANDWORM.get(),SandwormRenderer::new);e.registerEntityRenderer(CleopatraEntities.SCORPION.get(),ScorpionRenderer::new);e.registerEntityRenderer(CleopatraEntities.VENOM_BULLET.get(),c->new FlatRenderer<>(c,new ResourceLocation("yellowduck","textures/entity/elite_venom_bullet.png"),.35f,false));e.registerEntityRenderer(CleopatraEntities.VENOM_POOL.get(),c->new FlatRenderer<>(c,new ResourceLocation("yellowduck","textures/entity/elite_pool_purple.png"),2f,true));e.registerEntityRenderer(CleopatraEntities.VENOM_RING_FIRE.get(),RingRenderer::new);e.registerEntityRenderer(CleopatraEntities.VENOM_RING_ICE.get(),RingRenderer::new);e.registerEntityRenderer(CleopatraEntities.VENOM_RING_PLAIN.get(),RingRenderer::new);e.registerEntityRenderer(CleopatraEntities.BOMB_MARK_POISON.get(),BombRenderer::new);e.registerEntityRenderer(CleopatraEntities.BOMB_MARK_BURNING.get(),BombRenderer::new);e.registerEntityRenderer(CleopatraEntities.BOMB_MARK_FROZEN.get(),BombRenderer::new);e.registerEntityRenderer(CleopatraEntities.SNAKE_SUMMONER.get(),NoRenderer::new);}
static class BossRenderer extends GltfEntityRenderer<CleopatraBoss>{
private static final float MODEL_SCALE=.1f;
private static final double BBOX_CENTER_X=-10.2684006690979D;
private static final double BBOX_CENTER_Z=-2.2494001388549805D;
BossRenderer(EntityRendererProvider.Context c){super(c,new ResourceLocation("yellowduck","cleopatra_embedded"),GltfRenderOptions.builder().scale(MODEL_SCALE).shaderCompatMode(GltfRenderOptions.ShaderCompatMode.FORCE_CPU).preferGpuAnimatedMeshes(false).preferGpuStaticMeshes(false).build());}
@Override protected float renderYawDegrees(CleopatraBoss entity,float entityYaw,float partialTick){return 0.0F;}
@Override public void render(CleopatraBoss x,float y,float p,PoseStack ps,MultiBufferSource b,int l){AnimationController c=getAnimationController(x);if(c!=null){String a=switch(x.getAttackState()){case 2->"Attack1";case 3->"Attack2";case 4->"Attack3";default->x.isDeadOrDying()?"Death":"Idle";};if(!a.equals(c.getAnimationName()))c.play(a,a.equals("Idle"));}float yaw=Mth.rotLerp(p,x.yRotO,x.getYRot());ps.pushPose();ps.mulPose(Axis.YP.rotationDegrees(-yaw));ps.translate(BBOX_CENTER_X*MODEL_SCALE,0.0D,BBOX_CENTER_Z*MODEL_SCALE);super.render(x,0.0F,p,ps,b,l);ps.popPose();}}
static class SnakeRenderer extends GltfEntityRenderer<CleopatraVenomSnake>{
private static final float MODEL_SCALE=.1f;
private static final double BBOX_CENTER_X=0.0D;
private static final double BBOX_CENTER_Z=-6.653698921203613D;
SnakeRenderer(EntityRendererProvider.Context c,String m){super(c,new ResourceLocation("yellowduck",m),GltfRenderOptions.builder().scale(MODEL_SCALE).shaderCompatMode(GltfRenderOptions.ShaderCompatMode.FORCE_CPU).preferGpuAnimatedMeshes(false).preferGpuStaticMeshes(false).build());}
@Override protected float renderYawDegrees(CleopatraVenomSnake entity,float entityYaw,float partialTick){return 0.0F;}
@Override public void render(CleopatraVenomSnake x,float y,float p,PoseStack ps,MultiBufferSource b,int l){AnimationController c=getAnimationController(x);if(c!=null){String a=x.isDeadOrDying()?"Death":switch(x.getAttackState()){case 1->"Appear";case 2->"Attack";default->"Idle";};if(!a.equals(c.getAnimationName()))c.play(a,a.equals("Idle"));}float yaw=Mth.rotLerp(p,x.yRotO,x.getYRot());ps.pushPose();ps.mulPose(Axis.YP.rotationDegrees(-yaw));ps.translate(BBOX_CENTER_X*MODEL_SCALE,0.0D,BBOX_CENTER_Z*MODEL_SCALE);super.render(x,0.0F,p,ps,b,l);ps.popPose();}}
static class SandwormModel extends GeoModel<CleopatraSandworm>{public ResourceLocation getModelResource(CleopatraSandworm a){return new ResourceLocation("yellowduck","geo/entity/cleopatra_sandworm.geo.json");}public ResourceLocation getTextureResource(CleopatraSandworm a){return new ResourceLocation("yellowduck","textures/entity/cleopatra_sandworm.png");}public ResourceLocation getAnimationResource(CleopatraSandworm a){return new ResourceLocation("yellowduck","animations/entity/cleopatra_sandworm.animation.json");}}
static class SandwormRenderer extends GeoEntityRenderer<CleopatraSandworm>{SandwormRenderer(EntityRendererProvider.Context c){super(c,new SandwormModel());}}
static class ScorpionModel extends GeoModel<CleopatraScorpion>{public ResourceLocation getModelResource(CleopatraScorpion a){return new ResourceLocation("yellowduck","geo/entity/cleopatra_scorpion.geo.json");}public ResourceLocation getTextureResource(CleopatraScorpion a){return new ResourceLocation("yellowduck","textures/entity/cleopatra_scorpion.png");}public ResourceLocation getAnimationResource(CleopatraScorpion a){return new ResourceLocation("yellowduck","animations/entity/cleopatra_scorpion.animation.json");}}
static class ScorpionRenderer extends GeoEntityRenderer<CleopatraScorpion>{ScorpionRenderer(EntityRendererProvider.Context c){super(c,new ScorpionModel());}}
static class FlatRenderer<T extends Entity> extends EntityRenderer<T>{final ResourceLocation tex;final float size;final boolean horizontal;FlatRenderer(EntityRendererProvider.Context c,ResourceLocation t,float s,boolean h){super(c);tex=t;size=s;horizontal=h;}public ResourceLocation getTextureLocation(T e){return tex;}@Override public void render(T e,float yaw,float pt,PoseStack ps,MultiBufferSource bs,int light){ps.pushPose();ps.translate(0,.05,0);if(horizontal)ps.mulPose(Axis.XP.rotationDegrees(90));else ps.mulPose(entityRenderDispatcher.cameraOrientation());ps.scale(size,size,size);Matrix4f m=ps.last().pose();VertexConsumer v=bs.getBuffer(RenderType.entityTranslucent(getTextureLocation(e)));v.vertex(m,-.5f,-.5f,0).color(255,255,255,255).uv(0,1).overlayCoords(OverlayTexture.NO_OVERLAY).uv2(light).normal(0,1,0).endVertex();v.vertex(m,.5f,-.5f,0).color(255,255,255,255).uv(1,1).overlayCoords(OverlayTexture.NO_OVERLAY).uv2(light).normal(0,1,0).endVertex();v.vertex(m,.5f,.5f,0).color(255,255,255,255).uv(1,0).overlayCoords(OverlayTexture.NO_OVERLAY).uv2(light).normal(0,1,0).endVertex();v.vertex(m,-.5f,.5f,0).color(255,255,255,255).uv(0,0).overlayCoords(OverlayTexture.NO_OVERLAY).uv2(light).normal(0,1,0).endVertex();ps.popPose();super.render(e,yaw,pt,ps,bs,light);}}
static class RingRenderer extends FlatRenderer<CleopatraVenomRing>{RingRenderer(EntityRendererProvider.Context c){super(c,new ResourceLocation("yellowduck","textures/entity/elite_ring_plain.png"),4f,true);}@Override public ResourceLocation getTextureLocation(CleopatraVenomRing e){return new ResourceLocation("yellowduck","textures/entity/"+(e.getKind()==0?"elite_ring_fire.png":e.getKind()==1?"elite_ring_ice.png":"elite_ring_plain.png"));}}
static class BombRenderer extends FlatRenderer<CleopatraBombMark>{BombRenderer(EntityRendererProvider.Context c){super(c,new ResourceLocation("yellowduck","textures/entity/bomb_mark_poison.png"),.8f,false);}@Override public ResourceLocation getTextureLocation(CleopatraBombMark e){return new ResourceLocation("yellowduck","textures/entity/"+(e.getKind()==1?"bomb_mark_burning.png":e.getKind()==2?"bomb_mark_frozen.png":"bomb_mark_poison.png"));}}
static class NoRenderer extends EntityRenderer<CleopatraSnakeSummoner>{NoRenderer(EntityRendererProvider.Context c){super(c);}public ResourceLocation getTextureLocation(CleopatraSnakeSummoner e){return new ResourceLocation("minecraft","textures/misc/white.png");}}
}
